In [7]:
import torch
import numpy as np
from data_processing import *
import scipy.io as spio
from torch.nn import functional as F

In [3]:
def cross_entropy(y_true,y_pred):
    C=0
    # one-hot encoding
    for col in range(y_true.shape[-1]):
        y_pred[col] = y_pred[col] if y_pred[col] < 1 else 0.99999
        y_pred[col] = y_pred[col] if y_pred[col] > 0 else 0.00001
        C+=y_true[col]*torch.log(y_pred[col])+(1-y_true[col])*torch.log(1-y_pred[col])
    return -C

In [4]:
y_pred = torch.randn(16, 64, 4, 4)
y_true = torch.ones(16, 64, 4).type(torch.long)

In [22]:
x = torch.randn(4, 2)
y = torch.randn(4, 4)
z = torch.matmul(y ,x)

# z = y * x
print (x)
torch.linalg.inv(y) @ z


tensor([[-0.5684,  1.7172],
        [ 0.1426, -0.8755],
        [ 0.0956, -0.3135],
        [ 1.0988, -0.4396]])


tensor([[-0.5684,  1.7172],
        [ 0.1426, -0.8755],
        [ 0.0956, -0.3135],
        [ 1.0988, -0.4396]])

In [25]:
a = torch.tensor([[[2, 3], [4, 5]],[[6, 7], [8, 9]]])
a.reshape(4, 2)

tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
symbol_num, carrier_num, Nr, M = y_pred.shape
loss = []
for i in range (symbol_num):
    for j in range (carrier_num):
        for k, cls in enumerate (y_true[i, j]):
            x_class = -y_pred[i, j, k][cls]
            log_x_j = torch.log( 
                sum(
                    [torch.exp(l) for l in y_pred[i, j, k]]
                )
            )
            loss.append(x_class + log_x_j)
loss = torch.tensor(loss, dtype=torch.float32)
print (torch.mean(loss))

tensor(1.7039)


In [13]:
_loss = torch.nn.CrossEntropyLoss()
print (_loss(
    y_pred.permute(0, 3, 1, 2),
    y_true
))
print (_loss(
    y_pred.reshape(16, 4, 64, 4),
    y_true
))

tensor(1.7039)
tensor(1.7103)


In [17]:
x = np.array([[[1,2], [3,4], [5,6]], [[7, 8], [9,10], [11,12]]])

In [89]:
x.reshape(6, 2)
from torch import nn

In [96]:
conv1 = nn.Conv1d(in_channels=256,out_channels=512,kernel_size=2)
input = torch.randn(100,256,4)
# batch_size x text_len x embedding_size -> batch_size x embedding_size x text_len
out = conv1(input)
print(out.size())
conv2 = nn.ConvTranspose1d (512, 256, kernel_size=2)
out2 = conv2(out)
print (out2.shape)

torch.Size([100, 512, 3])
torch.Size([100, 256, 4])


In [107]:
loss = nn.CrossEntropyLoss()
x = torch. randn(16, 256, 4)
x = x.permute(0, 2, 1)
print (x.shape)
y = torch.randn(16, 256).type(torch.long)
loss(x, y)

IndexError: Target -1 is out of bounds.

In [128]:
y = torch.randn(16, 64, 4, 2)


In [131]:
embed = nn.Embedding(2, 128)


In [132]:
_y = embed(y)

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [125]:
_, _idx = torch.max (y, 2)

In [127]:
print (y[0, 7, :])
_idx[0, 7]

tensor([ 0.1087, -0.4365,  0.4903, -0.1312])


tensor(2)

In [133]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

/opt/anaconda3/lib/python3.9/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))


tensor([1.], device='mps:0')
